name: ML-Test
on: [push]
jobs:
  run: 
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      env: 
        repo_token: ${{secrets.GITHUB_TOKEN}} 
    - name: Create and fix permissions
      run: |
        mkdir -p /github/home/.cache/pip
        sudo chown -R $(whoami) /github/home/.cache/pip
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: "Test ML-Model"
      run: |
        python model/model.py
     