name: Code Quality Check
on:
  push:
    branches: [main]
    
jobs:
  build-and-test:
      runs-on: [ubuntu-latest]
      container: docker://dvcorg/cml-py3:latest
      steps:
        - name: Caching von pip Abhängigkeiten
          uses: actions/cache@v3
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{hashFiles('requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
          env:
            GITHUB_TOKEN: "${{secrets.WORKFLOW_TOKEN}}"
        
        - uses: actions/checkout@v3
          env:
           repo_token: ${{secrets.WORKFLOW_TOKEN }}
          with:
            sparse-checkout: |
              .github/workflows/*
              requirements.txt
              data/reports_data/*
              data/plot_data/*
              data/plots_balanced/*
              data/plot_data/*
              data/reports_data/*
              data/IDs/*
              data/train-test-data/*
              data/train-test-data/train/*
              data/train-test-data/test/*
              data/train-test-data/train/men/*
              data/train-test-data/train/women/*
              data/train-test-data/test/women/*
              data/train-test-data/test/men/*
              data/source_csv/*
              test/*
              data/dataprep_scripts/*
              data/balanced_source_csv/*
              report_activation.md
              report_data_plots.md
              report_data_plots.md
              report_distribution.md
              report_ml.md
              report_test_rauschen.md
              report_test_verzerrung.md
              report_rotation.md
              model/*
              reports/*
              deploy/*
        - name: Abhängigkeiten installieren
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt


        - name: Radon
          env:
            repo_token: ${{secrets.WORKFLOW_TOKEN}}
          run: |
            chmod +x .github/workflows/radon.sh
            ./.github/workflows/radon.sh
            
        # - name: Push
        #   env:
        #     repo_token: ${{ secrets.WORKFLOW_TOKEN }}
        #   run: |
        #     git config --local user.email "Aseuc@github.com"
        #     git config --local user.name "Aseuc"
        #     git add radon_tests/output_radon_cc_max.txt 
        #     git add radon_tests/output_radon_mi_max.txt 
        #     git add radon_tests/output_radon_raw_max.txt
        #     git commit -m "Add generated files" 
        #     git commit -a -m "Update radon outputs"
        #     git push origin Gender_Dataset_kaggle_23000