name: Code Quality Check
on:
  push:
    branches: [Gender_Dataset_kaggle_23000]
    
jobs:
  build-and-test:
      runs-on: [ubuntu-latest]
      container: docker://dvcorg/cml-py3:latest
      steps:
        - name: Caching von pip Abhängigkeiten
          uses: actions/cache@v3
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{hashFiles('requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
          env:
            GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
        
        - uses: actions/checkout@v3
          env:
           repo_token: ${{ secrets.GITHUB_TOKEN }}

        - name: Abhängigkeiten installieren
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt


        - name: Radon
          env:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
          run: |
            chmod +x .github/workflows/radon.sh
            ./.github/workflows/radon.sh
            