name: Code Quality Check
on:
  push:
    branches: [Gender_Dataset_kaggle_23000]

jobs:
  benchmark:
    runs-on: [ubuntu-latest]
    # container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   sparse-checkout: |
        #     .github/workflows/radon.sh
        #     model/model_script/model_train.py
        #     deploy/deploy.py
        #     test/model_test_scripts/model_test.py 
        #     data/dataprep_scripts/datapreparation.py
        #     radon_tests/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Code Quality Check
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install radon
          python_files=("model/model_script/model_train.py" "deploy/deploy.py" "data/dataprep_scripts/datapreparation.py", "test/model_test_scripts/model_test.py")

# Run radon cc
for python_file in "${python_files[@]}"; do
    datetime=$(date +%Y%m%d_%H%M%S)
    output_file_cc="radon_tests/output_cc_max.txt"
    radon cc ${python_file} > ${output_file_cc}
done

# Run radon raw
for python_file in "${python_files[@]}"; do
    datetime=$(date +%Y%m%d_%H%M%S)
    output_file_raw="radon_tests/output_raw_max.txt"
    radon raw ${python_file} > ${output_file_raw}
done

# Run radon mi
for python_file in "${python_files[@]}"; do
    datetime=$(date +%Y%m%d_%H%M%S)
    output_file_mi="radon_tests/output_mi_max.txt"
    radon mi ${python_file} > ${output_file_mi}
done
