name: Benchmark
on:
  push:
    branches: [Gender_Dataset_kaggle_23000]

jobs:
  benchmark:
    name: Check performance regeression.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github/workflows/*
            deploy/deploy.py
            model/model_scripts/model_train.py
            deploy/dataprep_scripts/*
            test/model_test_scripts/*
            data/dataprep_scripts/*
      - name: Run benchmark
        run: |
          chmod +x radon.sh
          ./.github/workflows/radon.sh