name: Code Quality Check
on:
  push:
    branches: [fdg]

jobs:
  benchmark:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github/workflows/radon.sh
            deploy/deploy.py
            model/model_scripts/model_train.py
            deploy/dataprep_scripts/*
            test/model_test_scripts/*
            data/dataprep_scripts/*
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Code Quality Check
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install radon
          chmod +x radon.sh
          ./.github/workflows/radon.sh