name: Main Workflow



on:
    push:
        branches: test

jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run top command
      run: top -b -n 1