name: Main Workflow



on:
    push:
        branches: sdf

jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with: 
        sparse-checkout: |
          .github/workflows/

    - name: Run top command
      run: top -b -n 1