name: Data Preparation Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dataprep.txt

    - name: Run dataprep.py and push selected images
      run: |
        python data/dataprep.py
        git config --local user.email "Aseuc@github.com"
        git config --local user.name "Aseuc"
     
        git commit -a "Add selected images"
        git push origin main