name: Data Preparation Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dataprep.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies 
        env:
            GITHUB_TOKEN: ${{ secrets.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 }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dataprep.txt
          python data/dataprep.py

      - name: Commit and push
        run: |
            git config --local user.email "Aseuc@github.com"
            git config --local user.name "Aseuc"
            git add .
            git commit -m "Add generated file" -a || echo "No changes to commit"
            git remote set-url origin https://$GITHUB_TOKEN@github.com/Aseuc/CICD-Pipeline-Gender-Recognition.git
            git push