name: ML-Workflow
on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
      
      - name: Install CML
        run: |
          curl -s -O https://cml.dev/install
          sh install
        shell: bash


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run data preparation
        run: |
          python data/dataprep.py
     
      - name: Train model
        run: |
          python model/train.py
          
      - name: Test model
        run: |
          python test/validate_model.py

      - name: Upload plot
        uses: actions/upload-artifact@v2
        with:
          name: Validate Plot
          path: test/plot.png
  
      - name: Generate and publish report
        run: |
          echo "## Model Performance" >> report.md
          cml-publish test/plot.png --md >> report.md

      - name: Comment report
        run: |
          cml-send-comment report.md

      - name: Commit and push model from train.py
        run: |
          git config --local user.email "Aseuc@github.com"
          git config --local user.name "Aseuc"
          git add .
          git commit -m "Add generated file" -a || echo "No changes to commit"
          git push origin main
      
    
      - name: Create new branch
        run: |
          BRANCH_NAME=$(date +%Y%m%d%H%M%S)
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          