name: mlops-exaple-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert
          jupyter nbconvert --to script model/pytorch_train.ipynb
          python model/pytorch_train.py

          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
              
          cml-send-comment report.md
        
          
          