name: ML-Train
on:
  push:
    branches:
      - test_torch-new-workflow

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Test CML
        env:
          GITHUB_TOKEN: ${{secrets.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 }}
        run: |
     
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          
          cml-publish model/plot_truelabelVSpredictions.jpg --md >> report.md
          
          cml-send-comment report.md
          
      - name: Commit and push changes
        run: |
          git config --local user.email "Aseuc@github.com"
          git config --local user.name "Aseuc"
          git add .
          git commit -m "Add generated file" -a || echo "No changes to commit"
          git push origin ${{ github.ref }}
        
          
          