name: ML-Train mit Performance-Report
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert

      - name: 'Prepare data'
        run: |
          jupyter nbconvert --to script data/dataprep_git.ipynb 
          python data/dataprep_git.py 

      - name: 'Train my model'
        run: |
          jupyter nbconvert --to script model/pytorch_train.ipynb
          python model/pytorch_train.py

          echo "## Model Metriken" > report.md
          cat metrics.txt >> report.md
          
          echo "\n## Model Performance" >> report.md
          echo "Modell Performance bzw. das Matching zwischen Predictions und True-Labels in einer Heatmap dargestellt!" >> report.md
          cml-publish model/heatmap.jpg --md >> report.md
          
          echo "\n## Model Performance" >> report.md
          echo "Modell Performance in einem Scatter-Plot dargestellt" >> report.md
          cml-publish model/plot_scatter.jpg --md >> report.md
        
          echo "\n## Model Performance" >> report.md
          echo "Modell Performance in einem normalen Plot dargestellt" >> report.md
          cml-publish model/plot_plt.jpg --md >> report.md
      
          cml-send-comment report.md

      - name: Commit and push model from train.py
        run: |
          git config --local user.email "Aseuc@github.com"
          git config --local user.name "Aseuc"
          git add .
          git commit -m "Add generated file" -a || echo "No changes to commit"
          git push origin test_torch-new-workflow  
  



      
          