name: mlops-exaple-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert
          jupyter nbconvert --to script model/pytorch_train.ipynb
          python model/pytorch_train.py

          echo "## Model Metriken" > report.md
          cat metrics.txt >> report.md
          
          echo "\n## Model Performance" >> report.md
          echo "Modell Performance in eine Scatter Plot dargestellt" >> report.md
          
          cml-publish model/plot_scatter.jpg --md >> report.md



           
          echo "\n## Model Performance" >> report.md
          echo "Modell Performance in einem normalen Plot dargestellt" >> report.md
          cml-publish model/plot_plt.jpg --md >> report.md


          cml-send-comment report.md
        
          
          