name: CI-CD-Workflow Gender Recognition
on:
  push:
    branches: [test]
    
jobs:
    build:
      runs-on: ubuntu-latest
        
      steps:
        - uses: actions/checkout@v3
          with: 
            sparse-checkout: 
                .github/workflows/

  
        - name: Run Prometheus
          run: |
            docker run \
              --publish=9090:9090 \
              --detach=true \
              --name=prometheus \
              prom/prometheus
  
        - name: Run cAdvisor
          run: |
            docker run \
              --volume=/:/rootfs:ro \
              --volume=/var/run:/var/run:rw \
              --volume=/sys:/sys:ro \
              --volume=/var/lib/docker/:/var/lib/docker:ro \
              --publish=8080:8080 \
              --detach=true \
              --name=cadvisor \
              google/cadvisor:latest \
              --storage_driver=prometheus \
              --storage_driver_host=localhost:9090
  
        - name: Export Grafana dashboard as PDF
          run: |
            # This is a placeholder. You need to use a tool or script to export the dashboard as PDF.
            # For example, you could use the Grafana API and a tool like wkhtmltopdf.
  
        - name: Upload Grafana dashboard as artifact
          run: |
            git config --local user.email "Aseuc@github.com"
            git config --local user.name "Aseuc"
            git add ./dashboard.pdf
            git commit -m "Add Grafana dashboard"
            git push