name: CI-CD-Workflow Gender Recognition
on:
  push:
    branches: [asdf]
    
jobs:
    build:
      runs-on: ubuntu-latest
        
      steps:
        - uses: actions/checkout@v3
          with: 
            sparse-checkout: 
                .github/workflows/

  
        - name: Run Prometheus
          run: |
            docker run \
              --publish=9090:9090 \
              --detach=true \
              --name=prometheus \
              prom/prometheus
  
        - name: Run cAdvisor
          run: |
            docker run \
              --volume=/:/rootfs:ro \
              --volume=/var/run:/var/run:rw \
              --volume=/sys:/sys:ro \
              --volume=/var/lib/docker/:/var/lib/docker:ro \
              --publish=8080:8080 \
              --detach=true \
              --name=cadvisor \
              google/cadvisor:latest \
              --storage_driver=prometheus \
              --storage_driver_host=localhost:9090
  
        - name: Export Grafana dashboard as PDF
          run: |
            sudo apt-get update -y
            sudo apt-get install -y wkhtmltopdf
            # Download the dashboard as a PNG image
            curl -H "Authorization: Bearer YOUR_API_KEY" http://localhost:3000/api/dashboards/home
            
            # Convert the PNG image to PDF
            wkhtmltopdf dashboard.png dashboard.pdf
  
        - name: Upload Grafana dashboard as artifact
          run: |
            git config --local user.email "Aseuc@github.com"
            git config --local user.name "Aseuc"
            git add ./dashboard.pdf
            git commit -m "Add Grafana dashboard"
            git push