name: CI-CD-Workflow Gender Recognition
on:
  push:
    branches: [asdf]
    
jobs:
  build-and-test:
      runs-on: [ubuntu-latest]
      container: docker://dvcorg/cml-py3:latest
      steps:
        - uses: actions/checkout@v3
          with:
            sparse-checkout: |
              .github
              data/new_test_dataset/train-test-data/*
              model/*
              test/*

        - name: Run Prometheus
          run: |
            docker run \
              --publish=9090:9090 \
              --detach=true \
              --name=prometheus \
              prom/prometheus

        - name: Run cAdvisor
          run: |
            docker run \
              --volume=/:/rootfs:ro \
              --volume=/var/run:/var/run:rw \
              --volume=/sys:/sys:ro \
              --volume=/var/lib/docker/:/var/lib/docker:ro \
              --publish=8080:8080 \
              --detach=true \
              --name=cadvisor \
              google/cadvisor:latest \
              --storage_driver=prometheus \
              --storage_driver_host=localhost:9090


        - name: ShellSkript Test
          env:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            WORKFLOW_TOKEN: ${{secrets.WORKFLOW_TOKEN }}

          run: |
            #   Uncomment the lines below to install dependencies
            #   python -m pip install --upgrade pip
            #   pip install -r requirements.txt
           
            #   chmod +x .github/workflows/model_metrics.sh
            #   ./.github/workflows/model_metrics.sh
            pip install torch torchvision tqdm matplotlib numpy pandas fairlearn sklearn torchcam
            python model/model_script/model_train.py 
            # python test/model_test_scripts/model_test.py 
            cml-publish 
            git config --local user.email "Aseuc@github.com"
            git config --local user.name "Aseuc"
            git add .
            git commit -m "Add generated file" -a || echo "No changes to commit"
            git push origin main
  
