name: Sparse Checkout

on:
  push:
    branches: [ new_dataset ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Sparse Checkout
      run: |
        git config core.sparseCheckout true
        echo "-git\info" > .git/info/sparse-checkout
        git read-tree -mu HEAD