name: CI-CD-Workflow Gender Recognition
on:
  push:
    branches: [test]
    
jobs:
  build-and-test:
      runs-on: [ubuntu-latest]
      container: docker://dvcorg/cml-py3:latest
      steps:
        - uses: actions/checkout@v3
          with:
            sparse-checkout: |
              .github
              data/new_test_dataset/train-test-data/*
              model/*
              test/*

        - name: Run cAdvisor
          run: |
            docker run \
              --volume=/:/rootfs:ro \
              --volume=/var/run:/var/run:rw \
              --volume=/sys:/sys:ro \
              --volume=/var/lib/docker/:/var/lib/docker:ro \
              --publish=8080:8080 \
              --detach=true \
              --name=cadvisor \
              google/cadvisor:latest



        - name: ShellSkript Test
          env:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            WORKFLOW_TOKEN: ${{secrets.WORKFLOW_TOKEN }}

          run: |
            #   Uncomment the lines below to install dependencies
            #   python -m pip install --upgrade pip
            #   pip install -r requirements.txt
           
            #   chmod +x .github/workflows/model_metrics.sh
            #   ./.github/workflows/model_metrics.sh
            pip install torch torchvision tqdm matplotlib numpy pandas fairlearn sklearn torchcam
            python model/model_script/model_train.py 
            # python test/model_test_scripts/model_test.py 

            git add model/PyTorch_Trained_Models
            git commit -m "Add new model"
            git push origin test
