
name: Sparse Checkout

on:
  push:
    branches: [ new_dataset ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1  # Shallow clones should be disabled for a full clone

      - name: Configure Sparse Checkout
        run: |
          git config core.sparseCheckout true
          echo "path/to/include" > .git/info/sparse-checkout
          git read-tree -mu HEAD