name: ML-Train mit Performance-Report
on: 
  push:
    branches:
      - t1
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    strategy:
      matrix:
        i: [1, 2, 3, 4]
    steps:
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}

      - name: Publish files
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
         
          echo "Running with i = ${{ matrix.i }}"
          # Hier können Sie Ihre Befehle hinzufügen, z.B.:
          cml-publish "test/test-plots-rauschen/${{ matrix.i }}.png" --md >> $report_file
       
      
          cml-send-comment report_test.md
        
    



      
          