name: ML CI/CD Pipeline

on:
  push:
    branches:
      - test

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run code check
        run: flake8 .

  unit-tests:
    needs: code-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest
        
        model-training:
            needs: unit-tests
            runs-on: ubuntu-latest
            steps:
              - name: Checkout code
                uses: actions/checkout@v2
        
              - name: Set up Python
                uses: actions/setup-python@v2
                with:
                  python-version: 3.8
        
              - name: Install dependencies
                run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
        
              - name: Train model               
                run: python model/train.py

            model-validation:
            needs: model-training
            runs-on: ubuntu-latest
            steps:
              - name: Checkout code
                uses: actions/checkout@v2
        
              - name: Set up Python
                uses: actions/setup-python@v2
                with:
                  python-version: 3.8
        
              - name: Install dependencies
                run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
        
              - name: Validate model
                run: python validate.py