name: ML-Train mit Performance-Report
on: 
  push:
    branches:
      - t1
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish files
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
         
          report_file="report_test.md"

          for file in test/test-plots-rauschen/*.png; do
            echo "Publishing $file"
            cml-publish "$file" --md >> $report_file
          done
          
          cml-send-comment report_test.md

    



      
          